spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  data:
    web:
      pageable:
        #Paging index가 1부터 시작(web으로부터 넘어올때)
        one-indexed-parameters: true
        default-page-size: 5

  datasource:
    url: jdbc:h2:mem:myLibrary
    username: sa
    password:
    driver-class-name: org.h2.Driver
